### ISSUE TITLE
Tracing performance

### ISSUE THREAD

**Issue by koekeishiya** [FelixKratz/JankyBorders#1]
Firstly, thank you for taking the initiative in creating these kinds of applications.

I have some old border code laying around that uses most of the private events that you do in this project, and I noticed a fair bit of difference in the delay when moving a window around the screen. I've attached two gifs; the first is my throwaway proof of concept and the other is commit https://github.com/FelixKratz/JankyBorders/commit/110b01ce2e6b359053550d16271bc768f3af5b5d

old poc: 
![throwaway](https://github.com/FelixKratz/JankyBorders/assets/6175959/b80be82e-9d85-4dc1-9ddd-8c154d14af1a)

this project:
![jankborders](https://github.com/FelixKratz/JankyBorders/assets/6175959/eba88499-54f6-411c-be7f-3d1cde80533e)

I haven't really looked at the code in detail, so can't really tell why there is that much of a difference.

My old throwaway project also uses `SLSRegisterNotifyProc(global_handler, 806, NULL);` to respond to window move events to re-align the border.

**Comment by FelixKratz** [comment]
Thanks for the heads up. I am not dragging windows with the mouse that much myself (thanks to your awesome tools).

This was probably due to my border update code being too conservative. I have implemented a separate function to handle the window move event now and it seems to be on par with what you have shown in your gif:


https://github.com/FelixKratz/JankyBorders/assets/22680421/a762a5b2-ec05-4b37-b4aa-9f9d9aed693a

**Comment by koekeishiya** [comment]
That looks a lot better yeah.

**Comment by FelixKratz** [comment]
Contained in v1.0.1 released just now.
