### ISSUE TITLE
Feature Request: Square borders

### ISSUE THREAD

**Issue by rockofox** [FelixKratz/JankyBorders#11]
I'm not sure if this is in scope for this project, but I'd love to see square borders akin to older versions of yabai, [cxa's yabai fork](https://github.com/cxa/yabai/tree/master) and tiling WMs on Linux.

**Comment by FelixKratz** [comment]
I will add an option for square borders later today, however, I will probably do it a bit different than the alternatives you have mentioned.

**Comment by rockofox** [comment]
Awesome! Thanks for the quick response

**Comment by FelixKratz** [comment]
I have added this just now. The way this differs from other implementations is that the border is only square on the outside but is still rounded on the inside. This is because the standard macOS windows are rounded and else there could be gaps between the window and the border if the border width is too small.

**Comment by net** [comment]
Is it possible to draw the borders over their windows and inset from their windows edge? This would let square borders cover up their windows' rounded corners.

**Comment by FelixKratz** [comment]
See #37 for details about how to achieve truely square borders.

**Comment by ELLIOTTCABLE** [comment]
I understand it's an unsupported feature, so zero judgement if you read this comment and close the tab without replying -

In at least two cases, I have actual apps that *themselves* have square borders, lol (why is UI-paradigm-adherence on macOS such a mess):

<details open><summary>Steam:</summary><img width="167" height="82" alt="Image" src="https://github.com/user-attachments/assets/9b05ac58-414c-40e0-98fe-5e22e390a2ae" /></details>

<details open><summary>Universal Audio's UAD Console:</summary><img width="262" height="123" alt="Image" src="https://github.com/user-attachments/assets/27c10d53-ddda-4d95-9e1c-b7a47051db79" /></summary>

Since the \~unsupported hack\~ is gated behind specific width, these look very strange if I *do* enable 'square' borders:

<details open><summary>UAD Console w/ <code>order=above style=square width=8.0</code>:</summary><img width="226" height="170" alt="Image" src="https://github.com/user-attachments/assets/82e6683a-217e-434e-9bc1-82a3c119c05f" /></details>

Would a PR simply enabling the precise current behaviour under `style=unsupported-square` instead/in-addition to `order=above style=square width=8.0` be welcome? Maintenance burden, user expectations, etc, I get it, no hard feelings if it's a "nope."

----

**Edit:** Okay, upon further investigation, I'm not sure I actually understand what the unsupported-hack is supposed to be doing. Even at `width=9.0`-and-above, the inner-radius is still curved; and even at `width=7.0`-and-below, the outer-radius is squared-off. Maybe it's something you removed since then?
