### ISSUE TITLE
[FR] Dynamically switch borders colors based on System's current colorscheme

### ISSUE THREAD

**Issue by Write** [FelixKratz/JankyBorders#46]
I would love to be able to define in the config file a color for both light and dark mode, and that it would switch automatically based on that whenever system color scheme switch.

Example

```
active_color_light
active_color_dark
inactive_color_light
inactive_color_dark
```

Thanks !

**Comment by FelixKratz** [comment]
This should be delegated to some kind of script. Because the border color can be changed on the fly you only need a script that reacts to the theme change, e.g. by using hammerspoon or sketchybar to listen to the `AppleInterfaceThemeChangedNotification` sent to the NSDistributedNotificationCenter.

**Comment by pvinis** [comment]
For anyone looking for a solution, I made [dark-scripter](https://github.com/pvinis/dark-scripter), a small utility that listens for macOS appearance changes and runs scripts in `~/.config/dark-scripter/`.

Create `~/.config/dark-scripter/borders.sh`:

```bash
#!/usr/bin/env bash
if [ "$DARKMODE" = "1" ]; then
  color="glow(0xffFF60D0)"
else
  color="glow(0xffC040A0)"
fi

/opt/homebrew/opt/borders/bin/borders "active_color=$color"
```

Then `chmod +x ~/.config/dark-scripter/borders.sh`.

One caveat: since this is an external script reacting to the notification, the color change applies on the next window focus, not immediately. If borders supported appearance-based colors natively, the change could be instant.
