### ISSUE TITLE
Inset borders

### ISSUE THREAD

**Issue by aspauldingcode** [FelixKratz/JankyBorders#89]
Please allow us to apply an inset border style.

**Comment by tanium-kdp** [comment]
Yes, this please. I use the tiler Divvy, and the majority of the borders are invisible (either off-screen or under a closely-placed window).

**Comment by FelixKratz** [comment]
Could you elaborate what exactly you mean by "inset border style"?

**Comment by tanium-kdp** [comment]
So, my understanding of this is: The 'inset border' would occupy / cover only the pixels occupied by the original window -- rather than being *around* the window, the highlighting would be *within* it. So, if I had two windows side-by-side each occupying 50% of the screen, the entire border of the active window would be visible. Presently, most of the pixels spill off onto my other monitors. The inset style would work vastly better for those of us who have coerced the Mac's ridiculous window manager to be tiling; I do this via Divvy, but I'm aware that there are other third-party solutions.

**Comment by FelixKratz** [comment]
See this issue for more technical detail and especially the last comment if you want to have truly square borders (undocumented and unsupported options): https://github.com/FelixKratz/JankyBorders/issues/37

**Comment by tanium-kdp** [comment]
I still get minor 'spill' from one monitor to the next but that's pretty close to what I want ... However, now the borders flicker (e.g., as I'm typing this into Firefox, each keystroke (or, more likely, I'm assuming, each UI update that *results* from the keystrokes) causes the border to flash).

**Comment by FelixKratz** [comment]
Yes thats why it is unsupported and undocumented, see https://github.com/FelixKratz/JankyBorders/issues/37#issuecomment-1871262622
Its a technical limitation in macOS. There is nothing we can do about it.

**Comment by aspauldingcode** [comment]
okay. Order above and order below works for me.
what I'd like to see now: ability to shift the amount of pixels inwards/outwards the border draws.

**Comment by FelixKratz** [comment]
From the technical point of view this is just one line of code, however, it obviously only works if order=above, which is unsupported and undocumented because of severe technical limitations. So I am not sure it is the right path to include even more unsupported and undocumented arguments.

**Comment by aspauldingcode** [comment]
Hmm. Seems reasonable. 
But, if there's anyone in the world who could try, I believe it's you. 
You might find a way around those limitations(?) one day..
